name: bioFila
favicon: null
layout_spectrum: 0.6547174800653011
typography_spectrum: 0.6565185768995434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.044594328850507736
  lightness: 0.06947940844111145
  saturation: 0.6152763734571636
  rhythmicContrast: 0.24511879263445735
purpose: []
